### PR TITLE
Fix restore_game

### PR DESCRIPTION
**Pull request by livibetter**
It didn't work, so I just copied the part from `save_game`.

### CODE REVIEW

**Comment by sshipway** [comment]
I can't automerge this, there is a conflict.  I'll address this later

**Comment by livibetter** [comment]
@sshipway I'll resolve this, I am currently trying to remove K&R C, unnecessary `extern`. Actually, restructuring the files, split the `wand_head.h`.

I have found some issues, such the prototypes didn't match, the crypt invocation has the parameter to indicate encrypt or decrypt, but the function definition has no such parameter, I wonder if that's half-written code or some time along the development, it got accidentally messed up.

Also, pass code from clearing screen didn't work to jump screen, for screen two at least, not sure about other screens, but "chocolate chips" did taste nice.

Anyway, it could be a relatively large PR.

**Comment by sshipway** [comment]
There are going to be loads of problems, since the C syntax is 25y old, and has DOS compatibility stuff in it.  Anyway, many thanks for your work on this!  It is great to see the old code living again...

**Comment by livibetter** [comment]
The following comment above the function explains why the `crypt_file` doesn't have the extra parameter.

``` c
/* Uses seeded random xor to encrypt because setkey doesnt work on our
   system.                                                                 */
```

Someone edited the function and made mismatch type signatures with the different prototypes here and there -- not just this function, several, actually.  I was very confused. Anyway, it doesn't need the parameter, since it's using XOR.

I also realized there is `convert` and `passwords` tools. that would have to be fixed, although, I don't really sure what they are for.

**Comment by livibetter** [comment]
This will be resolved in #8, closing.

**Pull request closed without merging**
